blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://cpeditor.org/docs/faq
    about: You may find your question and the answer to it here.
  - name: Documentation
    url: https://cpeditor.org/docs
    about: The documentation tells you how to use CP Editor.
  - name: Discussions
    url: https://github.com/cpeditor/cpeditor/discussions
    about: Feel free to ask any questions here, or discuss with the developers.
