name: "CI: Build Test"

on:
  push:
    paths-ignore:
      - '*.md'
      - '*/*/*.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*/*/*.md'

jobs:
  build:
    name: "Auto Clang Format"
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: "Install clang-format-9"
      run: |
        apt update
        apt install clang-format-9
        
    - name: "git version"
      run: git --version

    - name: "git clang format"
      run: git clang-format -h
