name: "Release AUR package"

on:
  push:
#     tags:
#       - '*'


jobs:
  build:
    name: "Release AUR package"
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa 
        known_hosts: ${{ secrets.KNOWN_HOST }}

    - name: Set up Qt environment
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.14.1

    - name: Generate AUR files
      run: |
        mkdir build
        git submodule update --init
        cd build
        cmake ..

    - name: Fetch AUR Remote
      run: |
        git clone ssh://aur@aur.archlinux.org/cpeditor.git
        cd cpeditor
        rm PKGBUILD .SRCINFO
        mv ../build/aur/PKGBUILD .
        mv ../build/aur/.SRCINFO .

    - name: Publish to AUR
      run: |
        cd cpeditor
        git add .
        git commit -m "New update from CI"
        git push -u origin master
