name: "Release AUR package"

on:
  release:
    types:
      - published

jobs:
  aur:
    name: "Release AUR package"
    runs-on: "ubuntu-16.04"

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::$VERSION
          read STABLE_VERSION < .ci/STABLE_VERSION
          if [ "${VERSION:0:${#STABLE_VERSION}}" == "$STABLE_VERSION" ]; then
            echo ::set-output name=ISSTABLE::true
          else
            echo ::set-output name=ISSTABLE::false
          fi

      - name: Install SSH key
        if: steps.get_version.outputs.ISSTABLE == 'true'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOST }}

      - name: Fetch AUR Remote
        if: steps.get_version.outputs.ISSTABLE == 'true'
        run: |
          git clone ssh://aur@aur.archlinux.org/cpeditor.git

      - name: Update files
        if: steps.get_version.outputs.ISSTABLE == 'true'
        run: |
          wget -c https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/cpeditor-${{ steps.get_version.outputs.VERSION }}-full-source.tar.gz
          sha256sum=$(shasum -a 256 cpeditor-${{ steps.get_version.outputs.VERSION }}-full-source.tar.gz | cut -d ' ' -f 1)
          cd cpeditor
          cp ../.ci/aur/stable/PKGBUILD .
          cp ../.ci/aur/stable/.SRCINFO .
          sed -i "s/@PROJECT_VERSION@/${{ steps.get_version.outputs.VERSION }}/" PKGBUILD .SRCINFO
          sed -i "s/SKIP/${sha256sum}/" PKGBUILD .SRCINFO

      - name: Publish to AUR
        if: steps.get_version.outputs.ISSTABLE == 'true'
        run: |
          cd cpeditor
          git config --global user.email "ashar786khan@gmail.com"
          git config --global user.name "coder3101"
          git add .
          git commit -m "Update from CI: ${GITHUB_REF/refs\/tags\//}"
          git push -u origin master
