name: "Release AUR package"

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to release"
        required: true

jobs:
  aur:
    name: "Release AUR package"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          case "${{ github.event_name }}" in
            release) VERSION=${{ github.event.release.tag_name }};;
            workflow_dispatch) VERSION=${{ github.event.inputs.version }};;
          esac

          echo ::set-output name=version::$VERSION
          read STABLE_VERSION < .ci/STABLE_VERSION
          if [ "${VERSION:0:${#STABLE_VERSION}}" == "$STABLE_VERSION" ]; then
            echo ::set-output name=ISSTABLE::true
          else
            echo ::set-output name=ISSTABLE::false
          fi

      - name: Install SSH key
        if: steps.get_version.outputs.ISSTABLE == 'true'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOST }}

      - name: Fetch AUR Remote
        if: steps.get_version.outputs.ISSTABLE == 'true'
        run: |
          git clone ssh://aur@aur.archlinux.org/cpeditor.git

      - name: Update files
        if: steps.get_version.outputs.ISSTABLE == 'true'
        run: |
          git checkout ${{ steps.get_version.outputs.version }}
          wget -c https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/cpeditor-${{ steps.get_version.outputs.version }}-full-source.tar.gz
          sha256sum=$(shasum -a 256 cpeditor-${{ steps.get_version.outputs.version }}-full-source.tar.gz | cut -d ' ' -f 1)
          cd cpeditor
          cp ../.ci/aur/stable/PKGBUILD .
          cp ../.ci/aur/stable/.SRCINFO .
          sed -i "s/@PROJECT_VERSION@/${{ steps.get_version.outputs.version }}/g" PKGBUILD .SRCINFO
          sed -i "s/SKIP/${sha256sum}/g" PKGBUILD .SRCINFO

      - name: Check PKGBUILD
        if: steps.get_version.outputs.ISSTABLE == 'true'
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: "pkgbuild"
          pkgname: "cpeditor"

      - name: "Check .SRCINFO"
        if: steps.get_version.outputs.ISSTABLE == 'true'
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: "srcinfo"
          pkgname: "cpeditor"

      - name: Publish to AUR
        if: steps.get_version.outputs.ISSTABLE == 'true'
        run: |
          cd cpeditor
          git config --global user.email "ashar786khan@gmail.com"
          git config --global user.name "coder3101"
          git commit -am "Update from CI: ${{ steps.get_version.outputs.version }}"
          git push -u origin master
