name: "Release AUR package"

on:
  push:
#     tags:
#       - '*'


jobs:
  build:
    name: "Release AUR package"
    runs-on: 'ubuntu-latest'
    
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa 
        known_hosts: ${{ secrets.KNOWN_HOST }}

    - name: Generate AUR files
      run: |
        ls -l
        mkdir build
        cd build
        ls -l
        cmake ..

    - name: Fetch AUR Remote
      run: |
        git clone ssh://aur@aur.archlinux.org/cpeditor.git
        cd cpeditor
        rm PKGBUILD .SRCINFO
        mv ../build/aur/PKGBUILD
        mv ../build/aur/.SRCINFO

    - name: Publish to AUR
      run: |
        cd cpeditor
        git push -u origin master
